package com.test.fibonacci.handler;

import java.util.List;


/**
 * Describes the Fibonacci-related functionality handled by this application.
 */
public interface FibonacciHandler {

    /**
     * Gets the next element in the Fibonacci sequence for a given user.
     *
     * @param userId the ID of the user.
     * @return the {@code Long} value of the next Fibonacci element.
     * */
    Long handleGet(Long userId);

    /**
     * Lists the Fibonacci sequence generated by a given user.
     *
     * @param userId the ID of the user.
     * @return a {@code List} containing all the elements that are currently in the user's sequence.
     */
    List<Long> handleList(Long userId);

    /**
     * Sets the Fibonacci sequence index of a given user back with one position.
     *
     * @param userId the ID of the user.
     */
    void handleGoingBack(Long userId);
}